Champion.delete_all
Team.delete_all

def tier_color(tier)
  case tier
    when 1
      return "white"
    when 2
      return "green"
    when 3
      return "blue"
    when 4
      return "purple"
    when 5
      return "yellow"
  end
end

def player_damage(tier)
  case tier
    when 1
      return [1, 2, 4]
    when 2
      return [2, 3, 5]
    when 3
      return [2, 3, 6]
    when 4
      return [2, 4, 6]
    when 5
      return [3, 5, 8]
  end
end

#Champions
aatrox = Champion.create(
  id: 1,
  name: "Aatrox",
  icon: "./aatrox",
  ability_name: "The Darkin Blade",
  ability_icon: "./aatrox",
  ability_type: "Active",
  ability_description: "Aatrox cleaves the area in front of him, dealing damage to enemies inside it.",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Demon",
  character_class_1: "Blademaster",
  health: [700, 1350, 2700],
  starting_mana: 0,
  mana_cost: 75,
  attack_damage: 65,
  attack_speed: 0.65,
  attack_range: 1,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(3)
)
ahri = Champion.create(
  id: 2,
  name: "Ahri",
  icon: "./ahri",
  ability_name: "Orb of Deception",
  ability_icon: "./ahri",
  ability_type: "Active",
  ability_description: "Ahri fires an orb in a line that returns to her, damaging enemies it passes through.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Wild",
  character_class_1: "Sorcerer",
  health: [450, 810, 1620],
  starting_mana: 0,
  mana_cost: 75,
  attack_damage: 50,
  attack_speed: 0.55,
  attack_range: 3,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(2)
)
akali = Champion.create(
  id: 3,
  name: "Akali",
  icon: "./akali",
  ability_name: "Five Point Strike",
  ability_icon: "./akali",
  ability_type: "Active",
  ability_description: "Akali throws shurikens in front of her, dealing damage.",
  tier: 4,
  tier_color: tier_color(4),
  origin_1: "Ninja",
  character_class_1: "Assassin",
  health: [650, 1260, 2520],
  starting_mana: 0,
  mana_cost: 25,
  attack_damage: 80,
  attack_speed: 0.70,
  attack_range: 1,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(4)
)
anivia = Champion.create(
  id: 4,
  name: "Anivia",
  icon: "./anivia",
  ability_name: "Glacial Storm",
  ability_icon: "./anivia",
  ability_type: "Active",
  ability_description: "Anivia channels a large hailstorm, damaging enemies inside of it.",
  tier: 5,
  tier_color: tier_color(5),
  origin_1: "Glacial",
  character_class_1: "Elementalist",
  health: [700, 1170, 2340],
  starting_mana: 0,
  mana_cost: 100,
  attack_damage: 40,
  attack_speed: 0.60,
  attack_range: 3,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(5)
)
ashe = Champion.create(
  id: 5,
  name: "Ashe",
  icon: "./ashe",
  ability_name: "Enchanted Crystal Arrow",
  ability_icon: "./ashe",
  ability_type: "Active",
  ability_description: "Ashe fires an arrow that travels across the map, damages, and stuns (stun duration based on each hex traveled).",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Glacial",
  character_class_1: "Ranger",
  health: [550, 990, 1980],
  starting_mana: 0,
  mana_cost: 100,
  attack_damage: 65,
  attack_speed: 0.70,
  attack_range: 4,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(3)
)
aurelionsol = Champion.create(
  id: 6,
  name: "Aurelion Sol",
  icon: "./aurelionsol",
  ability_name: "The Voice of Light",
  ability_icon: "./aurelionsol",
  ability_type: "Active",
  ability_description: "Aurelion Sol breathes a large blast of fire in a line, dealing damage to enemies.",
  tier: 4,
  tier_color: tier_color(4),
  origin_1: "Dragon",
  character_class_1: "Sorcerer",
  health: [650, 1080, 2160],
  starting_mana: 0,
  mana_cost: 125,
  attack_damage: 40,
  attack_speed: 0.60,
  attack_range: 3,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(4)
)
blitzcrank = Champion.create(
  id: 7,
  name: "Blitzcrank",
  icon: "./blitzcrank",
  ability_name: "Rocket Grab",
  ability_icon: "./blitzcrank",
  ability_type: "Active",
  ability_description: "Blitzcrank pulls the furthest enemy to him.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Robot",
  character_class_1: "Brawler",
  health: [600, 1080, 2160],
  starting_mana: 0,
  mana_cost: 125,
  attack_damage: 50,
  attack_speed: 0.50,
  attack_range: 1,
  armor: 35,
  magic_resist: 20,
  player_damage: player_damage(2)
)
brand = Champion.create(
  id: 8,
  name: "Brand",
  icon: "./brand",
  ability_name: "Pyroclasm",
  ability_icon: "./brand",
  ability_type: "Active",
  ability_description: "Brand launches a bouncing fireball, damaging enemies hit.",
  tier: 4,
  tier_color: tier_color(4),
  origin_1: "Demon",
  character_class_1: "Elementalist",
  health: [700, 1260, 2520],
  starting_mana: 50,
  mana_cost: 150,
  attack_damage: 60,
  attack_speed: 0.60,
  attack_range: 3,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(4)
)
braum = Champion.create(
  id: 9,
  name: "Braum",
  icon: "./braum",
  ability_name: "Unbreakable",
  ability_icon: "./braum",
  ability_type: "Active",
  ability_description: "Braum creates a barrier that blocks a percentage of all incoming damage.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Glacial",
  character_class_1: "Guardian",
  health: [650, 1350, 2700],
  starting_mana: 0,
  mana_cost: 50,
  attack_damage: 40,
  attack_speed: 0.60,
  attack_range: 1,
  armor: 75,
  magic_resist: 20,
  player_damage: player_damage(2)
)
camille = Champion.create(
  id: 52,
  name: "Camille",
  icon: "./camille",
  ability_name: "The Hextech Ultimatum",
  ability_icon: "./camille",
  ability_type: "Active",
  ability_description: "Camille roots an enemy and forces her in-range teammates to target whomever she's fighting.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Hextech",
  character_class_1: "Blademaster",
  health: [550, 990, 1980],
  starting_mana: 0,
  mana_cost: 150,
  attack_damage: 50,
  attack_speed: 0.60,
  attack_range: 1,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(1)
)
chogath = Champion.create(
  id: 10,
  name: "Cho\'Gath",
  icon: "./chogath",
  ability_name: "Rupture",
  ability_icon: "./chogath",
  ability_type: "Active",
  ability_description: "Cho\'gath ruptures an area, knocking up and damaging enemies inside of it.",
  tier: 4,
  tier_color: tier_color(4),
  origin_1: "Void",
  character_class_1: "Brawler",
  health: [1000, 2000, 4000],
  starting_mana: 0,
  mana_cost: 150,
  attack_damage: 70,
  attack_speed: 0.60,
  attack_range: 1,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(4)
)
darius = Champion.create(
  id: 11,
  name: "Darius",
  icon: "./darius",
  ability_name: "Decimate",
  ability_icon: "./darius",
  ability_type: "Active",
  ability_description: "Darius swings his axe, damaging nearby enemies and healing himself based off his missing health.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Imperial",
  character_class_1: "Knight",
  health: [600, 1080, 2160],
  starting_mana: 0,
  mana_cost: 100,
  attack_damage: 50,
  attack_speed: 0.50,
  attack_range: 1,
  armor: 40,
  magic_resist: 20,
  player_damage: player_damage(1)
)
draven = Champion.create(
  id: 12,
  name: "Draven",
  icon: "./draven",
  ability_name: "Spinning Axes",
  ability_icon: "./draven",
  ability_type: "Active",
  ability_description: "Draven gains bonus on-hit damage and Attack Speed. Stacks up to two times.",
  tier: 4,
  tier_color: tier_color(4),
  origin_1: "Imperial",
  character_class_1: "Blademaster",
  health: [650, 1260, 2520],
  starting_mana: 0,
  mana_cost: 50,
  attack_damage: 70,
  attack_speed: 0.75,
  attack_range: 3,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(4)
)
elise = Champion.create(
  id: 13,
  name: "Elise",
  icon: "./elise",
  ability_name: "Spider Form",
  ability_icon: "./elise",
  ability_type: "Active",
  ability_description: "Elise fires a cocoon stunning the nearest enemy and transforms, summoning 1-4 Spiderlings depending on level.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Demon",
  character_class_1: "Shapeshifter",
  health: [500, 900, 1800],
  starting_mana: 0,
  mana_cost: 100,
  attack_damage: 45,
  attack_speed: 0.70,
  attack_range: 2,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(2)
)
evelynn = Champion.create(
  id: 14,
  name: "Evelynn",
  icon: "./evelynn",
  ability_name: "Last Caress",
  ability_icon: "./evelynn",
  ability_type: "Active",
  ability_description: "Evelynn deals damage to the 3 closest enemies and teleports away. Damage is increased against low health enemies.",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Demon",
  character_class_1: "Assassin",
  health: [550, 990, 1980],
  starting_mana: 0,
  mana_cost: 75,
  attack_damage: 70,
  attack_speed: 0.60,
  attack_range: 1,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(3)
)
fiora = Champion.create(
  id: 15,
  name: "Fiora",
  icon: "./fiora",
  ability_name: "Riposte",
  ability_icon: "./fiora",
  ability_type: "Active",
  ability_description: "Fiora becomes immune to damage and spells. After a short delay, she stuns and damages the closest enemy.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Noble",
  character_class_1: "Blademaster",
  health: [400, 720, 1440],
  starting_mana: 0,
  mana_cost: 75,
  attack_damage: 40,
  attack_speed: 1.0,
  attack_range: 1,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(1)
)
gangplank = Champion.create(
  id: 16,
  name: "Gangplank",
  icon: "./gangplank",
  ability_name: "Powder Keg",
  ability_icon: "./gangplank",
  ability_type: "Passive/Active",
  ability_description: "Gangplank periodically creates barrels. On cast, Gangplank detonates the barrels, damaging nearby enemies.",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Pirate",
  character_class_1: "Blademaster",
  character_class_2: "Gunslinger",
  health: [700, 1080, 2160],
  starting_mana: 0,
  mana_cost: 100,
  attack_damage: 55,
  attack_speed: 0.65,
  attack_range: 1,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(3)
)
garen = Champion.create(
  id: 17,
  name: "Garen",
  icon: "./garen",
  ability_name: "Judgement",
  ability_icon: "./garen",
  ability_type: "Active",
  ability_description: "Garen rapidly spins his sword around his body, becoming immune to magic damage and dealing damage to nearby enemies.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Noble",
  character_class_1: "Knight",
  health: [600, 1080, 2160],
  starting_mana: 0,
  mana_cost: 100,
  attack_damage: 50,
  attack_speed: 0.60,
  attack_range: 1,
  armor: 40,
  magic_resist: 20,
  player_damage: player_damage(1)
)
gnar = Champion.create(
  id: 18,
  name: "Gnar",
  icon: "./gnar",
  ability_name: "GNAR!",
  ability_icon: "./gnar",
  ability_type: "Active",
  ability_description: "Gnar transforms and jumps behind the furthest enemy, damaging and shoving enemies backwards.",
  tier: 4,
  tier_color: tier_color(4),
  origin_1: "Wild",
  origin_2: "Yordle",
  character_class_1: "Shapeshifter",
  health: [750, 1530, 3060],
  starting_mana: 0,
  mana_cost: 125,
  attack_damage: 50,
  attack_speed: 0.70,
  attack_range: 2,
  armor: 30,
  magic_resist: 20,
  player_damage: player_damage(4)
)
graves = Champion.create(
  id: 19,
  name: "Graves",
  icon: "./graves",
  ability_name: "Buckshot",
  ability_icon: "./graves",
  ability_type: "Passive",
  ability_description: "Graves\' attacks deal splash damage to nearby enemies.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Pirate",
  character_class_1: "Gunslinger",
  health: [450, 900, 1800],
  starting_mana: 0,
  mana_cost: 0,
  attack_damage: 55,
  attack_speed: 0.55,
  attack_range: 1,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(1)
)
jayce = Champion.create(
  id: 53,
  name: "Jayce",
  icon: "./jayce",
  ability_name: "Mercury Cannon",
  ability_icon: "./jayce",
  ability_type: "Active",
  ability_description: "Jayce disrupts the enemy frontline by knocking back an enemy unit with his hammer. He then switches to his Mercury Cannon bringing increased attack speed and ranged damage.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Hextech",
  character_class_1: "Shapeshifter",
  health: [600, 1080, 2160],
  starting_mana: 0,
  mana_cost: 50,
  attack_damage: 55,
  attack_speed: 0.70,
  attack_range: 1,
  armor: 30,
  magic_resist: 20,
  player_damage: player_damage(2)
)
jinx = Champion.create(
  id: 54,
  name: "Jinx",
  icon: "./jinx",
  ability_name: "Get Excited!",
  ability_icon: "./jinx",
  ability_type: "Passive",
  ability_description: "Jinx Gets Excited after her first takedown, gaining bonus attack speed. If she scores a second takedown she pulls out Fishbones, her rocket launcher, causing her attacks to deal AoE damage.",
  tier: 4,
  tier_color: tier_color(4),
  origin_1: "Hextech",
  character_class_1: "Gunslinger",
  health: [550, 990, 1980],
  starting_mana: 0,
  mana_cost: 0,
  attack_damage: 75,
  attack_speed: 0.65,
  attack_range: 3,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(4)
)
karthus = Champion.create(
  id: 20,
  name: "Karthus",
  icon: "./karthus",
  ability_name: "Requiem",
  ability_icon: "./karthus",
  ability_type: "Active",
  ability_description: "Karthus deals damage to a number of random enemies after a long channel.",
  tier: 5,
  tier_color: tier_color(5),
  origin_1: "Phantom",
  character_class_1: "Sorcerer",
  health: [850, 1530, 3060],
  starting_mana: 40,
  mana_cost: 125,
  attack_damage: 65,
  attack_speed: 0.65,
  attack_range: 3,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(5)
)
kassadin = Champion.create(
  id: 21,
  name: "Kassadin",
  icon: "./kassadin",
  ability_name: "Nether Blade",
  ability_icon: "./kassadin",
  ability_type: "Passive",
  ability_description: "Kassadin\'s attacks steal mana from enemies, converting it into a shield.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Void",
  character_class_1: "Sorcerer",
  health: [550, 990, 1980],
  starting_mana: 0,
  mana_cost: 0,
  attack_damage: 55,
  attack_speed: 0.60,
  attack_range: 1,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(1)
)
katarina = Champion.create(
  id: 22,
  name: "Katarina",
  icon: "./katarina",
  ability_name: "Death Lotus",
  ability_icon: "./katarina",
  ability_type: "Active",
  ability_description: "Katarina channels and fires daggers at a number of nearby enemies, dealing damage and reducing healing.",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Imperial",
  character_class_1: "Assassin",
  health: [450, 810, 1620],
  starting_mana: 0,
  mana_cost: 100,
  attack_damage: 65,
  attack_speed: 0.65,
  attack_range: 1,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(3)
)
kayle = Champion.create(
  id: 23,
  name: "Kayle",
  icon: "./kayle",
  ability_name: "Divine Judgement",
  ability_icon: "./kayle",
  ability_type: "Active",
  ability_description: "Kayle shields an ally, making them immune to damage.",
  tier: 5,
  tier_color: tier_color(5),
  origin_1: "Noble",
  character_class_1: "Knight",
  health: [750, 1440, 2880],
  starting_mana: 0,
  mana_cost: 125,
  attack_damage: 70,
  attack_speed: 1.0,
  attack_range: 3,
  armor: 40,
  magic_resist: 20,
  player_damage: player_damage(5)
)
kennen = Champion.create(
  id: 24,
  name: "Kennen",
  icon: "./kennen",
  ability_name: "Slicing Maelstrom",
  ability_icon: "./kennen",
  ability_type: "Active",
  ability_description: "Kennen summons a storm around him, dealing damage and stunning enemies inside of it.",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Ninja",
  origin_2: "Yordle",
  character_class_1: "Elementalist",
  health: [550, 990, 1980],
  starting_mana: 0,
  mana_cost: 150,
  attack_damage: 65,
  attack_speed: 0.65,
  attack_range: 2,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(3)
)
khazix = Champion.create(
  id: 25,
  name: "Kha\'Zix",
  icon: "./khazix",
  ability_name: "Taste Their Fear",
  ability_icon: "./khazix",
  ability_type: "Active",
  ability_description: "Kha\'Zix slashes the closest enemy, dealing bonus damage to enemies that are alone.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Void",
  character_class_1: "Assassin",
  health: [500, 900, 1800],
  starting_mana: 0,
  mana_cost: 50,
  attack_damage: 55,
  attack_speed: 0.60,
  attack_range: 1,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(1)
)
kindred = Champion.create(
  id: 26,
  name: "Kindred",
  icon: "./kindred",
  ability_name: "Lamb\'s Respite",
  ability_icon: "./kindred",
  ability_type: "Active",
  ability_description: "Kindred creates a zone around herself that prevents allies from dying.",
  tier: 4,
  tier_color: tier_color(4),
  origin_1: "Phantom",
  character_class_1: "Ranger",
  health: [600, 1080, 2160],
  starting_mana: 0,
  mana_cost: 150,
  attack_damage: 60,
  attack_speed: 0.65,
  attack_range: 3,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(4)
)
leona = Champion.create(
  id: 27,
  name: "Leona",
  icon: "./leona",
  ability_name: "Solar Flare",
  ability_icon: "./leona",
  ability_type: "Active",
  ability_description: "Leona calls down a solar ray, stunning enemies in the center and dealing damage to enemies inside it.",
  tier: 4,
  tier_color: tier_color(4),
  origin_1: "Noble",
  character_class_1: "Guardian",
  health: [750, 1350, 2700],
  starting_mana: 0,
  mana_cost: 100,
  attack_damage: 45,
  attack_speed: 0.55,
  attack_range: 1,
  armor: 100,
  magic_resist: 20,
  player_damage: player_damage(4)
)
lissandra = Champion.create(
  id: 28,
  name: "Lissandra",
  icon: "./lissandra",
  ability_name: "Frozen Tomb",
  ability_icon: "./lissandra",
  ability_type: "Active",
  ability_description: "Lissandra encases the target in ice, dealing damage to nearby enemies. Below half HP, Lissandra instead encases herself, becoming untargetable.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Glacial",
  character_class_1: "Elementalist",
  health: [450, 810, 1620],
  starting_mana: 0,
  mana_cost: 125,
  attack_damage: 40,
  attack_speed: 0.60,
  attack_range: 2,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(2)
)
lucian = Champion.create(
  id: 29,
  name: "Lucian",
  icon: "./lucian",
  ability_name: "Relentless Pursuit",
  ability_icon: "./lucian",
  ability_type: "Active",
  ability_description: "Lucian dashes away to safety and attacks an enemy twice, once with Attack Damage and once with Spell Damage.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Noble",
  character_class_1: "Gunslinger",
  health: [600, 1080, 2160],
  starting_mana: 0,
  mana_cost: 35,
  attack_damage: 65,
  attack_speed: 0.65,
  attack_range: 3,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(2)
)
lulu = Champion.create(
  id: 30,
  name: "Lulu",
  icon: "./lulu",
  ability_name: "Wild Growth",
  ability_icon: "./lulu",
  ability_type: "Active",
  ability_description: "Lulu grants an ally bonus Health, knocking up enemies near them.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Yordle",
  character_class_1: "Sorcerer",
  health: [500, 900, 1800],
  starting_mana: 0,
  mana_cost: 150,
  attack_damage: 50,
  attack_speed: 0.60,
  attack_range: 2,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(2)
)
missfortune = Champion.create(
  id: 31,
  name: "Miss Fortune",
  icon: "./missfortune",
  ability_name: "Bullet Time",
  ability_icon: "./missfortune",
  ability_type: "Active",
  ability_description: "Miss Fortune channels and fires several waves of bullets in a cone.",
  tier: 5,
  tier_color: tier_color(5),
  origin_1: "Pirate",
  character_class_1: "Gunslinger",
  health: [700, 1170, 2340],
  starting_mana: 0,
  mana_cost: 75,
  attack_damage: 75,
  attack_speed: 0.85,
  attack_range: 3,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(5)
)
mordekaiser = Champion.create(
  id: 32,
  name: "Mordekaiser",
  icon: "./mordekaiser",
  ability_name: "Obliterate",
  ability_icon: "./mordekaiser",
  ability_type: "Active",
  ability_description: "Mordekaiser slams his mace in front him, dealing damage in a line.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Phantom",
  character_class_1: "Knight",
  health: [550, 900, 1800],
  starting_mana: 0,
  mana_cost: 100,
  attack_damage: 50,
  attack_speed: 0.50,
  attack_range: 1,
  armor: 40,
  magic_resist: 20,
  player_damage: player_damage(1)
)
morgana = Champion.create(
  id: 33,
  name: "Morgana",
  icon: "./morgana",
  ability_name: "Soul Shackles",
  ability_icon: "./morgana",
  ability_type: "Active",
  ability_description: "Morgana fires chains to nearby enemies, dealing damage and stunning after a short delay if they are still nearby.",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Demon",
  character_class_1: "Sorcerer",
  health: [650, 1170, 2340],
  starting_mana: 0,
  mana_cost: 150,
  attack_damage: 50,
  attack_speed: 0.60,
  attack_range: 2,
  armor: 30,
  magic_resist: 20,
  player_damage: player_damage(3)
)
nidalee = Champion.create(
  id: 34,
  name: "Nidalee",
  icon: "./nidalee",
  ability_name: "Primal Surge",
  ability_icon: "./nidalee",
  ability_type: "Active",
  ability_description: "Nidalee heals herself and the weakest ally, then transforms.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Wild",
  character_class_1: "Shapeshifter",
  health: [500, 900, 1800],
  starting_mana: 0,
  mana_cost: 100,
  attack_damage: 50,
  attack_speed: 0.65,
  attack_range: 3,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(1)
)
poppy = Champion.create(
  id: 35,
  name: "Poppy",
  icon: "./poppy",
  ability_name: "Keeper's Verdict",
  ability_icon: "./poppy",
  ability_type: "Active",
  ability_description: "Poppy brings down her hammer, knocking away and stunning nearby enemies.",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Yordle",
  character_class_1: "Knight",
  health: [800, 1440, 2880],
  starting_mana: 0,
  mana_cost: 75,
  attack_damage: 50,
  attack_speed: 0.50,
  attack_range: 1,
  armor: 40,
  magic_resist: 20,
  player_damage: player_damage(3)
)
pyke = Champion.create(
  id: 36,
  name: "Pyke",
  icon: "./pyke",
  ability_name: "Phantom Undertow",
  ability_icon: "./pyke",
  ability_type: "Active",
  ability_description: "Pyke dashes behind the furthest enemy, creating an afterimage that stuns enemies it passes through.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Pirate",
  character_class_1: "Assassin",
  health: [600, 1080, 2160],
  starting_mana: 0,
  mana_cost: 125,
  attack_damage: 60,
  attack_speed: 0.60,
  attack_range: 1,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(2)
)
reksai = Champion.create(
  id: 37,
  name: "Rek\'Sai",
  icon: "./reksai",
  ability_name: "Burrow",
  ability_icon: "./reksai",
  ability_type: "Active",
  ability_description: "Rek\'Sai burrows for a short duration becoming untargetable and healing. When Rek\'Sai unburrows she deals damage and knocks up the closest enemy.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Void",
  character_class_1: "Brawler",
  health: [650, 1170, 2340],
  starting_mana: 0,
  mana_cost: 150,
  attack_damage: 50,
  attack_speed: 0.65,
  attack_range: 1,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(2)
)
rengar = Champion.create(
  id: 38,
  name: "Rengar",
  icon: "./rengar",
  ability_name: "Savagery",
  ability_icon: "./rengar",
  ability_type: "Active",
  ability_description: "Rengar leaps to the weakest enemy and stabs them, he then gains an attack speed bonus.",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Wild",
  character_class_1: "Assassin",
  health: [550, 900, 1980],
  starting_mana: 0,
  mana_cost: 75,
  attack_damage: 70,
  attack_speed: 0.60,
  attack_range: 1,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(3)
)
sejuani = Champion.create(
  id: 39,
  name: "Sejuani",
  icon: "./sejuani",
  ability_name: "Glacial Prison",
  ability_icon: "./sejuani",
  ability_type: "Active",
  ability_description: "Sejuani creates a large glacial storm, stunning enemies within it after a short delay.",
  tier: 4,
  tier_color: tier_color(4),
  origin_1: "Glacial",
  character_class_1: "Knight",
  health: [850, 1530, 3060],
  starting_mana: 0,
  mana_cost: 150,
  attack_damage: 45,
  attack_speed: 0.55,
  attack_range: 1,
  armor: 40,
  magic_resist: 20,
  player_damage: player_damage(4)
)
shen = Champion.create(
  id: 40,
  name: "Shen",
  icon: "./shen",
  ability_name: "Spirit's Refuge",
  ability_icon: "./shen",
  ability_type: "Active",
  ability_description: "Shen creates a zone around himself, allowing allies to dodge all attacks.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Ninja",
  character_class_1: "Blademaster",
  health: [700, 1170, 2340],
  starting_mana: 0,
  mana_cost: 150,
  attack_damage: 65,
  attack_speed: 0.70,
  attack_range: 1,
  armor: 30,
  magic_resist: 20,
  player_damage: player_damage(2)
)
shyvana = Champion.create(
  id: 41,
  name: "Shyvana",
  icon: "./shyvana",
  ability_name: "Dragon's Descent",
  ability_icon: "./shyvana",
  ability_type: "Active",
  ability_description: "Shyvana dashes away and transforms. While transformed, Shyvana's attacks become ranged and light the ground on fire.",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Dragon",
  character_class_1: "Shapeshifter",
  health: [650, 990, 1980],
  starting_mana: 0,
  mana_cost: 100,
  attack_damage: 50,
  attack_speed: 0.70,
  attack_range: 1,
  armor: 30,
  magic_resist: 20,
  player_damage: player_damage(3)
)
swain = Champion.create(
  id: 42,
  name: "Swain",
  icon: "./swain",
  ability_name: "Demonflare",
  ability_icon: "./swain",
  ability_type: "Active",
  ability_description: "Swain transforms, draining health from all nearby enemies.",
  tier: 5,
  tier_color: tier_color(5),
  origin_1: "Demon",
  origin_2: "Imperial",
  character_class_1: "Shapeshifter",
  health: [850, 1530, 3060],
  starting_mana: 0,
  mana_cost: 100,
  attack_damage: 65,
  attack_speed: 0.65,
  attack_range: 2,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(5)
)
tristana = Champion.create(
  id: 43,
  name: "Tristana",
  icon: "./tristana",
  ability_name: "Explosive Charge",
  ability_icon: "./tristana",
  ability_type: "Active",
  ability_description: "Tristana places a bomb on her current target that detonates after 4 attacks, damaging nearby enemies.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Yordle",
  character_class_1: "Gunslinger",
  health: [500, 900, 1800],
  starting_mana: 0,
  mana_cost: 50,
  attack_damage: 50,
  attack_speed: 0.65,
  attack_range: 4,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(1)
)
twistedfate = Champion.create(
  id: 51,
  name: "Twisted Fate",
  icon: "./twistedfate",
  ability_name: "Pick a Card",
  ability_icon: "./twistedfate",
  ability_type: "Active",
  ability_description: "Twisted Fate throws a card that either stuns, deals damage around his target, or restores mana to himself and nearby allies.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Pirate",
  character_class_1: "Sorcerer",
  health: [450, 810, 1620],
  starting_mana: 0,
  mana_cost: 50,
  attack_damage: 40,
  attack_speed: 0.75,
  attack_range: 3,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(2)
)
varus = Champion.create(
  id: 44,
  name: "Varus",
  icon: "./varus",
  ability_name: "Piercing Arrow",
  ability_icon: "./varus",
  ability_type: "Active",
  ability_description: "Varus charges and fires an arrow, dealing damage to all enemies in a line.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Demon",
  character_class_1: "Ranger",
  health: [500, 900, 1800],
  starting_mana: 0,
  mana_cost: 75,
  attack_damage: 50,
  attack_speed: 0.70,
  attack_range: 4,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(2)
)
vayne = Champion.create(
  id: 45,
  name: "Vayne",
  icon: "./vayne",
  ability_name: "Silver Bolts",
  ability_icon: "./vayne",
  ability_type: "Passive",
  ability_description: "Vayne deals bonus true damage every third attack based on the enemy's maximum health.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Noble",
  character_class_1: "Ranger",
  health: [550, 990, 1980],
  starting_mana: 0,
  mana_cost: 0,
  attack_damage: 40,
  attack_speed: 0.70,
  attack_range: 3,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(1)
)
veigar = Champion.create(
  id: 46,
  name: "Veigar",
  icon: "./veigar",
  ability_name: "Primordial Burst",
  ability_icon: "./veigar",
  ability_type: "Active",
  ability_description: "Veigar blasts an enemy with magical energy. This spell instantly kills if the enemy is a lower star level than Veigar.",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Yordle",
  character_class_1: "Sorcerer",
  health: [500, 810, 1620],
  starting_mana: 0,
  mana_cost: 75,
  attack_damage: 45,
  attack_speed: 0.55,
  attack_range: 3,
  armor: 20,
  magic_resist: 20,
  player_damage: player_damage(3)
)
vi = Champion.create(
  id: 55,
  name: "Vi",
  icon: "./vi",
  ability_name: "Assault and Battery",
  ability_icon: "./twistedfate",
  ability_type: "Active",
  ability_description: "Vi targets the farthest enemy and charges towards them, knocking aside and damaging every enemy along the way. Once she gets there, she knocks her target up and damages them.",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Hextech",
  character_class_1: "Brawler",
  health: [600, 1080, 2160],
  starting_mana: 75,
  mana_cost: 150,
  attack_damage: 55,
  attack_speed: 0.65,
  attack_range: 1,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(3)
)
volibear = Champion.create(
  id: 47,
  name: "Volibear",
  icon: "./volibear",
  ability_name: "Thunder Claws",
  ability_icon: "./volibear",
  ability_type: "Active",
  ability_description: "Volibear\'s attacks bounce between enemies.",
  tier: 3,
  tier_color: tier_color(3),
  origin_1: "Glacial",
  character_class_1: "Brawler",
  health: [750, 1170, 2340],
  starting_mana: 0,
  mana_cost: 75,
  attack_damage: 75,
  attack_speed: 0.55,
  attack_range: 1,
  armor: 30,
  magic_resist: 20,
  player_damage: player_damage(3)
)
warwick = Champion.create(
  id: 48,
  name: "Warwick",
  icon: "./warwick",
  ability_name: "Infinite Duress",
  ability_icon: "./warwick",
  ability_type: "Active",
  ability_description: "Warwick pounces onto the lowest health enemy, stunning and damaging them.",
  tier: 1,
  tier_color: tier_color(1),
  origin_1: "Wild",
  character_class_1: "Brawler",
  health: [600, 1080, 2160],
  starting_mana: 0,
  mana_cost: 150,
  attack_damage: 50,
  attack_speed: 0.60,
  attack_range: 1,
  armor: 30,
  magic_resist: 20,
  player_damage: player_damage(1)
)
yasuo = Champion.create(
  id: 49,
  name: "Yasuo",
  icon: "./yasuo",
  ability_name: "Steel Tempest",
  ability_icon: "./yasuo",
  ability_type: "Active",
  ability_description: "Yasuo stabs forward dealing damage. On third cast, Yasuo launches a tornado dealing damage and knocking up enemies in a line.",
  tier: 5,
  tier_color: tier_color(5),
  origin_1: "Exile",
  character_class_1: "Blademaster",
  health: [700, 1260, 2520],
  starting_mana: 0,
  mana_cost: 25,
  attack_damage: 75,
  attack_speed: 1.00,
  attack_range: 1,
  armor: 35,
  magic_resist: 20,
  player_damage: player_damage(5)
)
zed = Champion.create(
  id: 50,
  name: "Zed",
  icon: "./zed",
  ability_name: "Razor Shuriken",
  ability_icon: "./zed",
  ability_type: "Active",
  ability_description: "Zed fires a shuriken in a line, damaging enemies it passes through.",
  tier: 2,
  tier_color: tier_color(2),
  origin_1: "Ninja",
  character_class_1: "Assassin",
  health: [550, 900, 1800],
  starting_mana: 0,
  mana_cost: 75,
  attack_damage: 66,
  attack_speed: 0.70,
  attack_range: 1,
  armor: 25,
  magic_resist: 20,
  player_damage: player_damage(2)
)

#Origins
demon = Team.create(
  id: 1,
  name: "Demon",
  icon: "./demon",
  team_type: "Origin",
  description: "Attacks from Demons have a 40% chance to burn 20 mana from their target and return mana to the attacker.",
  upgrade_1_number: "2:",
  upgrade_1_description: "15 mana returned",
  upgrade_2_number: "4:",
  upgrade_2_description: "30 mana returned",
  upgrade_3_number: "6:",
  upgrade_3_description: "45 mana returned"
)
demon.champions << [aatrox, brand, elise, evelynn, morgana, swain, varus]
dragon = Team.create(
  id: 2,
  name: "Dragon",
  icon: "./dragon",
  team_type: "Origin",
  description: "While 2 Dragons are in play, all Dragons take 83% reduced magic damage"
)
dragon.champions << [aurelionsol, shyvana]
exile = Team.create(
  id: 3,
  name: "Exile",
  icon: "./exile",
  team_type: "Origin",
  description: "If an Exile has no adjacent allies at the start of combat, they gain a shield equal to a 100% max health"
)
exile.champions << [yasuo]
glacial = Team.create(
  id: 4,
  name: "Glacial",
  icon: "./glacial",
  team_type: "Origin",
  description: "On hit, Glacials have a chance to stun for 2 seconds",
  upgrade_1_number: "2:",
  upgrade_1_description: "20% chance",
  upgrade_2_number: "4:",
  upgrade_2_description: "30% chance",
  upgrade_3_number: "6:",
  upgrade_3_description: "45% chance"
)
glacial.champions << [anivia, ashe, braum, lissandra, sejuani, volibear]
hextech = Team.create(
  id: 24,
  name: "Hextech",
  icon: "./hextech",
  team_type: "Origin",
  description: "At the start of combat, launch a pulse bomb at a random enemy, temporarily disabling nearby enemy items for 8 seconds",
  upgrade_1_number: "2:",
  upgrade_1_description: "Affects units within 1 hex of the bomb",
  upgrade_2_number: "4:",
  upgrade_2_description: "Affects units within 2 hexes of the bomb"
)
hextech.champions << [camille, jayce, jinx, vi]
imperial = Team.create(
  id: 5,
  name: "Imperial",
  icon: "./imperial",
  team_type: "Origin",
  description: "A select number of Imperials deal double damage",
  upgrade_1_number: "2:",
  upgrade_1_description: "One random Imperial",
  upgrade_2_number: "4:",
  upgrade_2_description: "All Imperials"
)
imperial.champions << [darius, draven, katarina, swain]
ninja = Team.create(
  id: 6,
  name: "Ninja",
  icon: "./ninja",
  team_type: "Origin",
  description: "Ninjas gain a flat amount of Attack Damage and Ability Power",
  upgrade_1_number: "1:",
  upgrade_1_description: "This Ninja gains 50 attack damage/ability power",
  upgrade_2_number: "4:",
  upgrade_2_description: "All Ninjas gain 70 attack damage/ability power"
)
ninja.champions << [akali, kennen, shen, zed]
noble = Team.create(
  id: 7,
  name: "Noble",
  icon: "./noble",
  team_type: "Origin",
  description: "Grants 60 armor/magic resist and basic attacks restore 35 health on-hit",
  upgrade_1_number: "3:",
  upgrade_1_description: "A random ally",
  upgrade_2_number: "6:",
  upgrade_2_description: "All allies"
)
noble.champions << [fiora, garen, kayle, leona, lucian, vayne]
phantom = Team.create(
  id: 8,
  name: "Phantom",
  icon: "./phantom",
  team_type: "Origin",
  description: "While 2 Phantoms are in play, a random enemy will begin combat with 100 health",
)
phantom.champions << [karthus, kindred, mordekaiser]
pirate = Team.create(
  id: 9,
  name: "Pirate",
  icon: "./pirate",
  team_type: "Origin",
  description: "While 3 Pirates are in play, you begin each PvP round with a chest that grants between 0 and 4 gold"
)
pirate.champions << [gangplank, graves, missfortune, pyke, twistedfate]
robot = Team.create(
  id: 10,
  name: "Robot",
  icon: "./robot",
  team_type: "Origin",
  description: "Robots start combat at full mana"
)
robot.champions << [blitzcrank]
void = Team.create(
  id: 11,
  name: "Void",
  icon: "./void",
  team_type: "Origin",
  description: "While 3 Voidlings are in play, void units deal true damage"
)
void.champions << [chogath, kassadin, khazix, reksai]
wild = Team.create(
  id: 12,
  name: "Wild",
  icon: "./wild",
  team_type: "Origin",
  description: "Wildlings generate Fury on-hit, up to 5. Each stack gives 12% attack speed",
  upgrade_1_number: "2:",
  upgrade_1_description: "Fury benefits all allied Wildlings",
  upgrade_2_number: "4:",
  upgrade_2_description: "Fury benefits all allies"
)
wild.champions << [ahri, gnar, nidalee, rengar, warwick]
yordle = Team.create(
  id: 13,
  name: "Yordle",
  icon: "./yordle",
  team_type: "Origin",
  description: "Yordles have a chance to dodge enemy attacks",
  upgrade_1_number: "3:",
  upgrade_1_description: "30% chance",
  upgrade_2_number: "6:",
  upgrade_2_description: "55% chance"
)
yordle.champions << [gnar, kennen, lulu, poppy, tristana, veigar]

#Classes
assassin = Team.create(
  id: 14,
  name: "Assassin",
  icon: "./assassin",
  team_type: "Class",
  description: "Assassins have bonus critical strike damage",
  upgrade_1_number: "2:",
  upgrade_1_description: "+125% critical strike damage",
  upgrade_2_number: "6:",
  upgrade_2_description: "+350% critical strike damage"
)
assassin.champions << [akali, evelynn, katarina, khazix, pyke, rengar, zed]
blademaster = Team.create(
  id: 15,
  name: "Blademaster",
  icon: "./blademaster",
  team_type: "Class",
  description: "Blademasters have a 45% chance to perform a multi-attack",
  upgrade_1_number: "3:",
  upgrade_1_description: "Double strike",
  upgrade_2_number: "6:",
  upgrade_2_description: "Triple strike",
  upgrade_3_number: "9:",
  upgrade_3_description: "Quadruple Strike"
)
blademaster.champions << [aatrox, camille, draven, fiora, gangplank, shen, yasuo]
brawler = Team.create(
  id: 16,
  name: "Brawler",
  icon: "./brawler",
  team_type: "Class",
  description: "Brawlers gain additional maximum health",
  upgrade_1_number: "2:",
  upgrade_1_description: "+250 maximum health",
  upgrade_2_number: "4:",
  upgrade_2_description: "+500 maximum health",
  upgrade_3_number: "6:",
  upgrade_3_description: "+900 maximum health"
)
brawler.champions << [blitzcrank, chogath, reksai, vi, volibear, warwick]
elementalist = Team.create(
  id: 17,
  name: "Elementalist",
  icon: "./elementalist",
  team_type: "Class",
  description: "Beginning combat with 3 Elementalists will summon an Elemental adjacent to one of your Elementalists"
)
elementalist.champions << [anivia, brand, kennen, lissandra]
guardian = Team.create(
  id: 18,
  name: "Guardian",
  icon: "./guardian",
  team_type: "Class",
  description: "Beginning combat with 2 Guardians will grant 50 armor to all units that start adjacent to a Guardian"
)
guardian.champions << [braum, leona]
gunslinger = Team.create(
  id: 19,
  name: "Gunslinger",
  icon: "./gunslinger",
  team_type: "Class",
  description: "Gunslingers have a 50% chance for their attacks to hit additional enemies",
  upgrade_1_number: "2:",
  upgrade_1_description: "Attacks hit one additional random enemy",
  upgrade_2_number: "4:",
  upgrade_2_description: "Attacks hit two additional random enemies",
  upgrade_3_number: "6:",
  upgrade_3_description: "Attacks hit three additional random enemies"
)
gunslinger.champions << [gangplank, graves, jinx, lucian, missfortune, tristana]
knight = Team.create(
  id: 20,
  name: "Knight",
  icon: "./knight",
  team_type: "Class",
  description: "All allies ignore a flat amount of damage from all sources",
  upgrade_1_number: "2:",
  upgrade_1_description: "15 damage ignored",
  upgrade_2_number: "4:",
  upgrade_2_description: "30 damage ignored",
  upgrade_3_number: "6:",
  upgrade_3_description: "55 damage ignored"
)
knight.champions << [darius, garen, kayle, mordekaiser, poppy, sejuani]
ranger = Team.create(
  id: 21,
  name: "Ranger",
  icon: "./ranger",
  team_type: "Class",
  description: "Every 3 seconds, Rangers have a chance to gain double attack speed for 3 seconds",
  upgrade_1_number: "2:",
  upgrade_1_description: "25% chance",
  upgrade_2_number: "4:",
  upgrade_2_description: "65% chance"
)
ranger.champions << [ashe, kindred, varus, vayne]
shapeshifter = Team.create(
  id: 22,
  name: "Shapeshifter",
  icon: "./shapeshifter",
  team_type: "Class",
  description: "Shapeshifters gain bonus health and heal for that amount when activating their Special Ability",
  upgrade_1_number: "3:",
  upgrade_1_description: "60% bonus health",
  upgrade_2_number: "6:",
  upgrade_2_description: "120% bonus health"
)
shapeshifter.champions << [elise, gnar, jayce, nidalee, shyvana, swain]
sorcerer = Team.create(
  id: 23,
  name: "Sorcerer",
  icon: "./sorcerer",
  team_type: "Class",
  description: "Sorcerers grant bonus spell damage to their team",
  upgrade_1_number: "3:",
  upgrade_1_description: "+40% bonus spell damage",
  upgrade_2_number: "6:",
  upgrade_2_description: "+100% bonus spell damage"
)
sorcerer.champions << [ahri, aurelionsol, karthus, kassadin, lulu, morgana, twistedfate, veigar]
